-- ============================================================
-- database/seed/005_fix_keywords_and_relations.sql
-- 内容质量补强修复脚本
-- 执行时间：2026-04-20
-- 前提：004_fix_enum_dirty_data.sql 已执行
-- ============================================================
-- 本脚本包含两类修复：
--   A. 为缺 keywords 的问题自动生成关键词（从标题+答案提取）
--   B. 为无关联关系的问题建立 related 关联
--
-- 注意：keywords 自动生成需要 Python 脚本配合，
--       本 SQL 仅记录 B 类关联修复的结果。
--
-- ---- B类：关联关系补强（170条）----
-- 以下 INSERT 由 Python 脚本自动生成并已执行：
-- 关联关系总数：924 → 1094 条
-- 无关联问题：69 → 0 条
--
-- ---- A类：关键词补强（185条）----
-- 以下 UPDATE 由 Python 脚本自动执行，已完成：
--   - 提取规则：正则提取中文字词（2-6字），过滤停用词，按频率排序取前5个
--   - 185条问题已补全 keywords
--   - keywords 为空的问题：185 → 0 条
--
-- 可重放验证：
--   SELECT COUNT(*) FROM question_master WHERE keywords IS NULL OR keywords = '';
--   -- 期望输出：0
--
--   SELECT COUNT(*) FROM question_master WHERE id NOT IN (SELECT question_id FROM question_relation);
--   -- 期望输出：0
